### ISSUE TITLE
Export of Descriptions

### ISSUE THREAD

**Issue by LociStar** [stiffmeds/Obeliskial-Essentials#1]
Hi,

I know that in ACO the custom descriptions of some perks are saved inside a separate table/database. 
The PerkData gives the hint with the column "CustomDescription". For example the perkData with ID "mainperkbleed2b" has the value "customMainperkbleed2b" inside CustomDescription. So theoretically it should be possible to get this descriptions via the id.

Is it possible to add the descriptions to the export? (@stiffmeds do you still maintain this repo/ add features?)

**Comment by stiffmeds** [comment]
Not anytime soon!

However, MoreTranslations may have the text you want - check [here](https://github.com/stiffmeds/AcrossTheObelisk_MoreTranslations/blob/main/MoreTranslations_English/english.txt)
